ignore:
  - "miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt"
  - "miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt"
coverage:
    status:
      project: off
      patch: off
